networks:
  test:
    driver: bridge

services:
  miner1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M111
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: Bistro
      WALLET_HOTKEY: M111
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      ENABLE_LOKI: 'true'
      INFLUXDB_HOST: ${INFLUXDB_HOST:-localhost}
      INFLUXDB_PORT: ${INFLUXDB_PORT:-8086}
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE:-tplr}
      INFLUXDB_ORG: ${INFLUXDB_ORG:-tplr}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '3' ]
              capabilities: [ gpu ]

  miner2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M222
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: Bistro
      WALLET_HOTKEY: M222
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      ENABLE_LOKI: 'true'
      INFLUXDB_HOST: ${INFLUXDB_HOST:-localhost}
      INFLUXDB_PORT: ${INFLUXDB_PORT:-8086}
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE:-tplr}
      INFLUXDB_ORG: ${INFLUXDB_ORG:-tplr}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

  validator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-validator-V11
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: validator
      WALLET_NAME: Bistro
      WALLET_HOTKEY: V11
      CUDA_DEVICE: cuda:0
      NETWORK: test
      DEBUG: 'true'
      NETUID: 268
      HOST_CUDA_VERSION: 12.6
      ENABLE_LOKI: 'true'
      INFLUXDB_HOST: ${INFLUXDB_HOST:-localhost}
      INFLUXDB_PORT: ${INFLUXDB_PORT:-8086}
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE:-tplr}
      INFLUXDB_ORG: ${INFLUXDB_ORG:-tplr}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              capabilities: [ gpu ]
